### ISSUE TITLE
Error while sorting the list of reflections!

### ISSUE THREAD

**Issue by devAbnull** [sugarlabs/reflect#5]
Steps to produce:
1. Make a list of some reflections.
2. Delete some of these.
3. Try to sort by title or stars or date

Expected Result: The list gets sorted.

Observed Result: The list remains the same. Cursor turns busy and is not reseted.

The log shows this error when tried to sort by _title_:

`Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gi/overrides/GLib.py", line 633, in <lambda>
    return (lambda data: callback(*data), user_data)
  File "/home/broot/sugar-build/activities/Reflect.activity/activity.py", line 598, in _title_sort
    key=lambda item: item['title'].lower())
  File "/home/broot/sugar-build/activities/Reflect.activity/activity.py", line 598, in <lambda>
    key=lambda item: item['title'].lower())
KeyError: 'title'`

**Comment by devAbnull** [comment]
When tried to print the `self.reflection_data` in log, I found this:

`self.reflection_data = 
[{'activities': [None], 'obj_id': 'obj-5557', 'title': 'heyy', 'creation_time': 1457526054, 'modification_time': 1457526054, 'stars': 0}, {'deleted': True, 'obj_id': 'obj-7764'}, {u'activities': [None], u'title': u'asdasd', u'obj_id': u'obj-2052', u'creation_time': 1457525398, u'modification_time': 1457525398, u'stars': 0}, {u'activities': [None], u'title': u'asas', u'obj_id': u'obj-7842', u'creation_time': 1457525397, u'modification_time': 1457525397, u'stars': 0}]`

It seems that when we delete reflection, it is not removed from the `self.reflection_data`.
Instead the line [activity.py/#269](https://github.com/walterbender/reflect/blob/master/activity.py#L269)
overwrites and the keys like _title_, _stars_ and _modification_time_ are lost!
